### ISSUE TITLE
api 패스 변경

### ISSUE THREAD

**Issue by yoowonyoung** [wanna-go-home/lens_review_server#18]
- 기존 get all 같은건 클라에서 안씀(그럴 것 같음  @up0617  의견 바람)
    + 지금 우리 ux컨셉은 블라인드와 같으므로, 전체를 다 볼필요는 없고, 전체의 프리뷰는 필요할수 있지(나중에 페이지네이션 하더라도 무튼)
    + 전체의 프리뷰를 보다가 하나의 상세를 보는 컨셉 이기 때문
 
- 그래서 기존 get all 같은거 다 없애버리고, end point는 그대로 두고, 반환하는 데이터만 preview로 반환하자
    + 그래서 클라놈들아 @up0617  @rlarlvy153  의견 내놔라 서버는 동의 어 보감 했다

**Comment by yoowonyoung** [comment]
- 지금은 /api/lensinfo <- 이렇게 되있는데 ( + 파라미터 ) 이걸 /api/lenses/{id} 이렇게 바꿔야지
- 보드는 /api/boards/free 혹은 /api/boards/review 이쯤이 낫지 않을까?

**Comment by zamonia500** [comment]
GET /api/lensinfo -> /api/lens?level=full (모든 렌즈 정보 GET, 이 api는 필요 없을 것 같음.)
GET /api/lensinfo/preview -> /api/lens?level=preview
GET /api/lensinfo?id=1 -> /api/lens/1

---

GET /api/free-board -> GET /api/boards/free?level=full (모든 free board 정보 GET, 이 api는 필요 없을 것 같음)
GET /api/free-board/preview -> GET /api/boards/free?level=preview
POST /api/free-board -> POST /api/boards/free

GET /api/review-board -> GET /api/boards/review?level=full (모든 review board 정보 GET, 이 api는 필요 없을 것 같음)
GET /api/review-board/preview -> GET /api/boards/review?level=preview
POST /api/review-board -> POST /api/review

**Comment by yoowonyoung** [comment]
level이 타입? 을 나타내는것인가? 뭔가 좋긴한데 네이밍이 명확하진 않은듯 함 타입정도로 바꾸는게 어떠할까 함 ㅎㅎ
글구 boards 와 free-board / review-board를 구분 지은건 직관적이여서 좋은듯 함(api 패스만 봐도 어떤 데이터 줄지 바로 보임)
킹치만 boards는 free board / review board를 모두 포함하는 최상위 개념이기 때문에
그래서 위에서 boards/free/  boards/review 이런식으로 했고, 추후 새로운 보드가 추가되도 boards/newboard 정도로 해줄수 잇단 장점이있쥬
요고는 쪼끔 다른친구들의견도 들어보죠
@up0617 @rlarlvy153 @seonhee-kim  클라들 와서 어디가 좋을까 봐보셈
