### ISSUE TITLE
리뷰 쓰기 api 스웨거에 불필요한것 제거

### ISSUE THREAD

**Issue by rlarlvy153** [wanna-go-home/lens_review_server#31]
AS-IS
{
  "account": "string",
  "content": "string",
  "createdAt": "2020-11-05T06:17:35.701Z",
  "id": 0,
  "lensId": 0,
  "likeCnt": 0,
  "replyCnt": 0,
  "title": "string"
}

TO-BE
{
  "content": "string",
  "lensId": 0,
  "title": "string"
}

**Comment by yoowonyoung** [comment]
내가함

**Comment by yoowonyoung** [comment]
account -> 현재 접속중인 사용자
createdAt -> 현재 서버 시간
id -> 자동입력
likeCnt / replyCnt -> Default ( 0 )
으로 처리 함
